### ISSUE TITLE
Create an interactive mode

### ISSUE THREAD

**Issue by jigarius** [jigarius/gup#1]
Sometimes, one doesn't know how many levels up they want to move! So, having a command like `gup -i` (interactive mode) would be helpful 😆

**Comment by gardon** [comment]
Something like presenting a list:
```
(1) src  
(2) repo  
(3) user  
(4) / (root)  
Please type the number of your choice.
```

**Comment by jigarius** [comment]
Added support for an interactive mode. This can be used with the `--interactive` or `-i` flag. Here's an example:

```bash
/a/2/c/d/e $ gup -i
Choose a destination directory:
1) d
2) c
3) 2
4) a
```

Entering the number corresponding to a directory takes you there.
