### ISSUE TITLE
Allow arbitrary depth based on folder name

### ISSUE THREAD

**Issue by gardon** [jigarius/gup#2]
Say I am in folder `/home/user/project/docroot/modules/this`.
I could type `gup project` and go up to the `project` directory.

**Comment by jigarius** [comment]
Makes sense. So, the argument will be overloaded.
```bash
gup 3 # Goes 3 levels up
gup docroot # Goes to the nearest parent directory named docroot
```

**Comment by robert-ngo** [comment]
I would expect that when you type `gup docroot`, it takes you to the nearest `docroot` parent folder...
Auto-suggest parent dir name would be super nice ; ))

**Comment by jigarius** [comment]
My god! @robert-ngo autocomplete will be a new world to explore. I'll try that after I finish the basic functionality.

**Comment by jigarius** [comment]
Done. Updated the documentation accordingly.
